// src/modules/projects/seedData.ts
import { ProjectMachine, ProjectWorker, MachineRun } from './types';

export const INITIAL_MACHINES: ProjectMachine[] = [
  {
    id: 'm-01',
    name: 'CNC Vertical Machining Center',
    code: 'VMC-01',
    category: 'CNC Milling',
    status: 'Running',
    hourlyCost: 350,
    operatorCapacity: 2,
    location: 'Shop Floor - Bay A',
    notes: 'High precision 4-axis machine',
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'm-02',
    name: 'Hydraulic Press 150T',
    code: 'HP-150',
    category: 'Forming & Press',
    status: 'Running',
    hourlyCost: 200,
    operatorCapacity: 3,
    location: 'Press Line - Bay B',
    notes: 'Heavy stamping line',
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'm-03',
    name: 'Fiber Laser Cutting Machine',
    code: 'FLC-3015',
    category: 'Sheet Metal',
    status: 'Idle',
    hourlyCost: 500,
    operatorCapacity: 2,
    location: 'Fabrication Section',
    notes: '3kW Raycus Source',
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'm-04',
    name: 'CNC Lathe Machine',
    code: 'LATHE-02',
    category: 'Turning',
    status: 'Idle',
    hourlyCost: 250,
    operatorCapacity: 1,
    location: 'Turning Center',
    notes: 'Tooling checked',
    createdAt: Date.now() - 86400000 * 2,
  },
];

export const INITIAL_WORKERS: ProjectWorker[] = [
  {
    id: 'w-01',
    name: 'Rajesh Sharma',
    code: 'EMP-101',
    role: 'Lead CNC Operator',
    hourlyRate: 180,
    contact: '+91 98765 43210',
    department: 'Machining',
    isContract: false,
  },
  {
    id: 'w-02',
    name: 'Amit Verma',
    code: 'EMP-102',
    role: 'Machine Operator',
    hourlyRate: 140,
    contact: '+91 98765 43211',
    department: 'Machining',
    isContract: false,
  },
  {
    id: 'w-03',
    name: 'Sunil Yadav',
    code: 'EMP-103',
    role: 'Press Specialist',
    hourlyRate: 150,
    contact: '+91 98765 43212',
    department: 'Press Shop',
    isContract: false,
  },
  {
    id: 'w-04',
    name: 'Ramesh Kumar',
    code: 'CON-201',
    role: 'Helper / Loader',
    hourlyRate: 90,
    contact: '+91 98765 43213',
    department: 'Press Shop',
    isContract: true,
  },
  {
    id: 'w-05',
    name: 'Dinesh Patil',
    code: 'CON-202',
    role: 'Material Handler / Feeder',
    hourlyRate: 85,
    contact: '+91 98765 43214',
    department: 'Fabrication',
    isContract: true,
  },
];

// Sample active and past runs
const now = Date.now();
const twoHoursAgo = new Date(now - 2 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(); // ~1.58 hrs ago
const oneHourAgo = new Date(now - 1 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString();

export const INITIAL_RUNS: MachineRun[] = [
  {
    id: 'run-01',
    runNumber: 'RUN-2026-001',
    projectName: 'PO-892 Valve Body Machining',
    machineId: 'm-01',
    machineName: 'CNC Vertical Machining Center',
    machineCode: 'VMC-01',
    status: 'Running',
    startTime: twoHoursAgo,
    durationHours: 1.6,
    assignedEmployees: [
      {
        employeeId: 'w-01',
        name: 'Rajesh Sharma',
        role: 'Lead CNC Operator',
        hourlyRate: 180,
        wageEarned: 288,
      },
      {
        employeeId: 'w-02',
        name: 'Amit Verma',
        role: 'Machine Operator',
        hourlyRate: 140,
        wageEarned: 224,
      },
    ],
    totalLaborCost: 512,
    machineHourlyRate: 350,
    machineCost: 560,
    totalCost: 1072,
    notes: 'Batch A - In progress',
    createdAt: now - 6000000,
  },
  {
    id: 'run-02',
    runNumber: 'RUN-2026-002',
    projectName: 'PO-904 Bracket Stamping Line',
    machineId: 'm-02',
    machineName: 'Hydraulic Press 150T',
    machineCode: 'HP-150',
    status: 'Running',
    startTime: oneHourAgo,
    durationHours: 1.2,
    assignedEmployees: [
      {
        employeeId: 'w-03',
        name: 'Sunil Yadav',
        role: 'Press Specialist',
        hourlyRate: 150,
        wageEarned: 180,
      },
      {
        employeeId: 'w-04',
        name: 'Ramesh Kumar',
        role: 'Helper / Loader',
        hourlyRate: 90,
        wageEarned: 108,
      },
    ],
    totalLaborCost: 288,
    machineHourlyRate: 200,
    machineCost: 240,
    totalCost: 528,
    notes: 'Punching sheet steel brackets',
    createdAt: now - 3600000,
  },
  {
    id: 'run-03',
    runNumber: 'RUN-2026-000',
    projectName: 'PO-840 Flange Turning Job',
    machineId: 'm-04',
    machineName: 'CNC Lathe Machine',
    machineCode: 'LATHE-02',
    status: 'Completed',
    startTime: new Date(now - 86400000).toISOString(),
    endTime: new Date(now - 86400000 + 4.5 * 3600000).toISOString(),
    durationHours: 4.5,
    assignedEmployees: [
      {
        employeeId: 'w-02',
        name: 'Amit Verma',
        role: 'Machine Operator',
        hourlyRate: 140,
        wageEarned: 630,
      },
    ],
    totalLaborCost: 630,
    machineHourlyRate: 250,
    machineCost: 1125,
    totalCost: 1755,
    unitsProduced: 120,
    notes: 'Completed 120 units on spec',
    createdAt: now - 86400000,
  },
];

